server:
  port: 9002

spring:
  application:
    name: eureka-Hi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka
#    register-with-eureka: false
#    fetch-registry: false